# Generated by Django 5.2.5 on 2025-08-31 18:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('carrera', models.CharField(choices=[('Sistemas', 'Sistemas'), ('Industrial', 'Industrial'), ('Contabilidad', 'Contabilidad'), ('Otro', 'Otro')], max_length=30)),
                ('ciclo', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('correo', models.EmailField(max_length=254, unique=True)),
            ],
        ),
    ]
